import { Plant } from "./types";

/**
 * Données de plantation pour un climat France tempérée (océanique/continental).
 * Mois : 1 = janvier ... 12 = décembre.
 * Les dates sont des repères pour débutants ; à ajuster selon la météo locale
 * (voir le réglage de zone climatique).
 */
export const PLANTS: Plant[] = [
  // ---------------- LÉGUMES ----------------
  {
    id: "tomate",
    nom: "Tomate",
    category: "legume",
    emoji: "🍅",
    difficulty: "moyen",
    exposition: "soleil",
    semis: [3, 4],
    plantation: [5, 6],
    recolte: [7, 8, 9, 10],
    arrosage: "Régulier au pied, sans mouiller les feuilles. 2 à 3 fois/semaine en été.",
    sol: "Riche, bien drainé, enrichi en compost.",
    espacement: "50 à 70 cm entre les plants.",
    compagnonsFavorables: ["Basilic", "Œillet d'Inde", "Carotte", "Persil"],
    compagnonsDefavorables: ["Pomme de terre", "Concombre", "Fenouil"],
    conseils:
      "Semer sous abri (intérieur, 18-20°C) en mars, repiquer en pleine terre après les Saints de Glace (mi-mai), une fois tout risque de gel écarté. Tuteurer et supprimer les gourmands.",
    famille: "Solanacées",
    levee: "6 à 10 jours à 20°C",
    ravageurs: ["Mildiou", "Pucerons", "Doryphores"],
    besoinEau: "eleve",
    soins: [
      { mois: [5, 6], titre: "Tuteurer les plants" },
      { mois: [6, 7, 8], titre: "Supprimer les gourmands (pousses entre tige et branche)" },
      { mois: [7, 8], titre: "Surveiller le mildiou par temps humide" },
    ],
  },
  {
    id: "carotte",
    nom: "Carotte",
    category: "legume",
    emoji: "🥕",
    difficulty: "facile",
    exposition: "soleil",
    semis: [3, 4, 5, 6, 7],
    plantation: [],
    recolte: [6, 7, 8, 9, 10, 11],
    arrosage: "Garder le sol frais surtout à la levée. Modéré ensuite.",
    sol: "Léger, sableux, sans cailloux ni fumier frais.",
    espacement: "Éclaircir à 5 cm sur le rang, 25 cm entre les rangs.",
    compagnonsFavorables: ["Poireau", "Oignon", "Radis", "Tomate"],
    compagnonsDefavorables: ["Aneth", "Persil"],
    conseils:
      "Semer directement en pleine terre, en ligne, très peu profond. La levée est lente (2-3 semaines). Éclaircir pour de belles racines.",
    famille: "Apiacées",
    levee: "15 à 21 jours",
    ravageurs: ["Mouche de la carotte"],
    besoinEau: "moyen",
    soins: [
      { mois: [4, 5, 6, 7], titre: "Éclaircir les plants à 5 cm" },
      { mois: [5, 6], titre: "Associer aux poireaux/oignons contre la mouche" },
    ],
  },
  {
    id: "radis",
    nom: "Radis",
    category: "legume",
    emoji: "🌶️",
    difficulty: "facile",
    exposition: "soleil",
    semis: [3, 4, 5, 6, 7, 8, 9],
    plantation: [],
    recolte: [5, 6, 7, 8, 9, 10],
    arrosage: "Fréquent et régulier, sinon les radis deviennent piquants et creux.",
    sol: "Meuble, frais, ordinaire.",
    espacement: "Éclaircir à 3-4 cm.",
    compagnonsFavorables: ["Carotte", "Laitue", "Haricot", "Tomate"],
    compagnonsDefavorables: ["Concombre", "Courgette"],
    conseils:
      "Le légume idéal pour débuter : récolte en 3 à 5 semaines. Semer un peu toutes les 2 semaines pour en avoir en continu.",
    famille: "Brassicacées",
    levee: "3 à 5 jours",
    ravageurs: ["Altises (petits trous dans les feuilles)"],
    besoinEau: "moyen",
    soins: [
      { mois: [3, 4, 5, 6, 7, 8], titre: "Ressemer une ligne toutes les 2 semaines" },
    ],
  },
  {
    id: "courgette",
    nom: "Courgette",
    category: "legume",
    emoji: "🥒",
    difficulty: "facile",
    exposition: "soleil",
    semis: [4, 5],
    plantation: [5, 6],
    recolte: [6, 7, 8, 9, 10],
    arrosage: "Abondant et régulier au pied. Très gourmande en eau.",
    sol: "Riche, profond, beaucoup de compost.",
    espacement: "1 m entre les plants (la plante s'étale).",
    compagnonsFavorables: ["Haricot", "Maïs", "Capucine"],
    compagnonsDefavorables: ["Pomme de terre", "Concombre"],
    conseils:
      "Très productive : 1 ou 2 pieds suffisent. Récolter jeune (15-20 cm) et souvent pour stimuler la production.",
    famille: "Cucurbitacées",
    levee: "6 à 10 jours",
    ravageurs: ["Oïdium (feutrage blanc sur les feuilles)"],
    besoinEau: "eleve",
    soins: [
      { mois: [6, 7, 8, 9], titre: "Récolter souvent pour relancer la production" },
      { mois: [7, 8], titre: "Surveiller l'oïdium, aérer le feuillage" },
    ],
  },
  {
    id: "laitue",
    nom: "Laitue / Salade",
    category: "legume",
    emoji: "🥬",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [2, 3, 4, 5, 6, 7, 8, 9],
    plantation: [3, 4, 5, 6, 7, 8, 9],
    recolte: [4, 5, 6, 7, 8, 9, 10, 11],
    arrosage: "Régulier, le sol ne doit jamais sécher complètement.",
    sol: "Frais, riche en humus.",
    espacement: "25 à 30 cm entre les plants.",
    compagnonsFavorables: ["Radis", "Carotte", "Fraise", "Concombre"],
    compagnonsDefavorables: ["Persil", "Tournesol"],
    conseils:
      "Semer peu à la fois mais souvent pour étaler les récoltes. En plein été, préférer la mi-ombre pour éviter la montée en graine.",
    famille: "Astéracées",
    levee: "5 à 10 jours",
    ravageurs: ["Limaces", "Pucerons"],
    besoinEau: "moyen",
    soins: [
      { mois: [3, 4, 5, 6, 7, 8], titre: "Semer un petit lot toutes les 2-3 semaines" },
      { mois: [4, 5, 6, 9, 10], titre: "Protéger des limaces (jeunes plants)" },
    ],
  },
  {
    id: "haricot-vert",
    nom: "Haricot vert",
    category: "legume",
    emoji: "🫘",
    difficulty: "facile",
    exposition: "soleil",
    semis: [5, 6, 7],
    plantation: [],
    recolte: [7, 8, 9, 10],
    arrosage: "Régulier, surtout à la floraison et formation des gousses.",
    sol: "Léger, réchauffé, sans excès d'azote.",
    espacement: "Poquets de 5-6 graines tous les 40 cm.",
    compagnonsFavorables: ["Courgette", "Laitue", "Carotte", "Fraise"],
    compagnonsDefavorables: ["Oignon", "Ail", "Poireau"],
    conseils:
      "Semer directement quand le sol est réchauffé (mi-mai). Attendre que la terre ait au moins 12°C, sinon les graines pourrissent.",
    famille: "Fabacées (légumineuses)",
    levee: "8 à 12 jours",
    ravageurs: ["Pucerons noirs"],
    besoinEau: "moyen",
    soins: [
      { mois: [6, 7], titre: "Butter légèrement les pieds pour les stabiliser" },
      { mois: [7, 8, 9], titre: "Récolter tous les 2-3 jours, jeunes" },
    ],
  },
  {
    id: "pomme-de-terre",
    nom: "Pomme de terre",
    category: "legume",
    emoji: "🥔",
    difficulty: "facile",
    exposition: "soleil",
    semis: [],
    plantation: [3, 4, 5],
    recolte: [6, 7, 8, 9],
    arrosage: "Modéré. Plus important à la floraison.",
    sol: "Meuble, profond, plutôt léger.",
    espacement: "30-40 cm sur le rang, 60-70 cm entre rangs.",
    compagnonsFavorables: ["Haricot", "Chou", "Maïs"],
    compagnonsDefavorables: ["Tomate", "Courgette", "Concombre"],
    conseils:
      "Planter des plants (tubercules germés) à 10-15 cm de profondeur. Butter (ramener la terre au pied) quand la plante atteint 20 cm.",
    famille: "Solanacées",
    levee: "Levée 3 à 4 semaines après plantation",
    ravageurs: ["Doryphores", "Mildiou"],
    besoinEau: "moyen",
    soins: [
      { mois: [5, 6], titre: "Butter les pieds (ramener la terre au pied)" },
      { mois: [5, 6, 7], titre: "Surveiller et ramasser les doryphores" },
    ],
  },
  {
    id: "poireau",
    nom: "Poireau",
    category: "legume",
    emoji: "🧅",
    difficulty: "moyen",
    exposition: "soleil",
    semis: [2, 3, 4],
    plantation: [5, 6, 7],
    recolte: [9, 10, 11, 12, 1, 2],
    arrosage: "Régulier les premières semaines après repiquage.",
    sol: "Riche, profond, frais.",
    espacement: "10-15 cm sur le rang, 30 cm entre rangs.",
    compagnonsFavorables: ["Carotte", "Céleri", "Fraise", "Tomate"],
    compagnonsDefavorables: ["Haricot", "Pois"],
    conseils:
      "Semer en pépinière, puis repiquer en habillant les racines et le feuillage. Butter pour blanchir le fût. Très rustique, tient l'hiver dehors.",
    famille: "Alliacées",
    levee: "10 à 15 jours",
    ravageurs: ["Ver du poireau (mineuse)", "Teigne"],
    besoinEau: "moyen",
    soins: [
      { mois: [8, 9, 10], titre: "Butter pour blanchir le fût" },
      { mois: [9, 10], titre: "Surveiller le ver du poireau (filet anti-insecte)" },
    ],
  },
  {
    id: "epinard",
    nom: "Épinard",
    category: "legume",
    emoji: "🥬",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [3, 4, 8, 9],
    plantation: [],
    recolte: [5, 6, 10, 11, 4],
    arrosage: "Régulier, le sol doit rester frais.",
    sol: "Riche, frais, profond.",
    espacement: "Éclaircir à 10 cm.",
    compagnonsFavorables: ["Fraise", "Chou", "Radis", "Haricot"],
    compagnonsDefavorables: ["Betterave"],
    conseils:
      "Se cultive au printemps et en automne (la chaleur le fait monter en graine). Récolter feuille à feuille au fur et à mesure des besoins.",
    famille: "Chénopodiacées",
    levee: "7 à 14 jours",
    ravageurs: ["Mildiou", "Pucerons"],
    besoinEau: "moyen",
    soins: [
      { mois: [5, 6, 10, 11], titre: "Récolter feuille à feuille, jeunes" },
    ],
  },
  {
    id: "petit-pois",
    nom: "Petit pois",
    category: "legume",
    emoji: "🫛",
    difficulty: "facile",
    exposition: "soleil",
    semis: [2, 3, 4, 10, 11],
    plantation: [],
    recolte: [5, 6, 7],
    arrosage: "Modéré, plus à la floraison.",
    sol: "Léger, frais, peu fumé.",
    espacement: "Rangs espacés de 40-50 cm.",
    compagnonsFavorables: ["Carotte", "Radis", "Concombre", "Laitue"],
    compagnonsDefavorables: ["Oignon", "Ail", "Poireau"],
    conseils:
      "Semer directement en ligne. Les variétés à rames ont besoin d'un support (grillage, branches). Récolter régulièrement pour prolonger la production.",
    famille: "Fabacées (légumineuses)",
    levee: "8 à 15 jours",
    ravageurs: ["Oïdium", "Tordeuse du pois"],
    besoinEau: "moyen",
    soins: [
      { mois: [4, 5], titre: "Installer un support (rames, grillage)" },
      { mois: [5, 6, 7], titre: "Récolter régulièrement pour prolonger" },
    ],
  },
  {
    id: "betterave",
    nom: "Betterave",
    category: "legume",
    emoji: "🫜",
    difficulty: "facile",
    exposition: "soleil",
    semis: [4, 5, 6],
    plantation: [],
    recolte: [7, 8, 9, 10],
    arrosage: "Régulier pour éviter que la racine ne durcisse.",
    sol: "Profond, meuble, sans cailloux.",
    espacement: "Éclaircir à 10-15 cm.",
    compagnonsFavorables: ["Laitue", "Chou", "Oignon", "Haricot"],
    compagnonsDefavorables: ["Épinard", "Poireau"],
    conseils:
      "Semer directement. Éclaircir car chaque graine donne plusieurs plants. Récolter quand la racine fait la taille d'une balle de tennis.",
    famille: "Chénopodiacées",
    levee: "10 à 14 jours",
    ravageurs: ["Pégomyie (mouche de la betterave)"],
    besoinEau: "moyen",
    soins: [
      { mois: [5, 6], titre: "Éclaircir à 10-15 cm" },
    ],
  },
  {
    id: "oignon",
    nom: "Oignon",
    category: "legume",
    emoji: "🧅",
    difficulty: "facile",
    exposition: "soleil",
    semis: [2, 3],
    plantation: [3, 4, 9, 10],
    recolte: [7, 8, 9],
    arrosage: "Faible. Arrêter l'arrosage en fin de cycle.",
    sol: "Léger, drainé, sans fumure fraîche.",
    espacement: "10-12 cm sur le rang.",
    compagnonsFavorables: ["Carotte", "Betterave", "Laitue", "Fraise"],
    compagnonsDefavorables: ["Haricot", "Pois", "Chou"],
    conseils:
      "Le plus simple : planter des bulbilles (petits oignons) au printemps. Récolter quand le feuillage jaunit et se couche. Laisser sécher au soleil.",
    famille: "Alliacées",
    levee: "Reprise des bulbilles en ~2 semaines",
    ravageurs: ["Mouche de l'oignon", "Mildiou"],
    besoinEau: "faible",
    soins: [
      { mois: [7, 8], titre: "Coucher le feuillage puis récolter par temps sec" },
      { mois: [8], titre: "Faire sécher les bulbes au soleil avant stockage" },
    ],
  },
  {
    id: "courge",
    nom: "Courge / Potimarron",
    category: "legume",
    emoji: "🎃",
    difficulty: "facile",
    exposition: "soleil",
    semis: [4, 5],
    plantation: [5, 6],
    recolte: [9, 10],
    arrosage: "Abondant au pied, surtout en période sèche.",
    sol: "Très riche, beaucoup de compost.",
    espacement: "1 à 1,5 m (les plantes s'étalent beaucoup).",
    compagnonsFavorables: ["Maïs", "Haricot", "Capucine"],
    compagnonsDefavorables: ["Pomme de terre", "Concombre"],
    conseils:
      "Prévoir de la place : un pied couvre plusieurs m². Récolter avant les gelées, quand le pédoncule est sec. Se conserve plusieurs mois au sec.",
    famille: "Cucurbitacées",
    levee: "6 à 10 jours",
    ravageurs: ["Oïdium"],
    besoinEau: "eleve",
    soins: [
      { mois: [9, 10], titre: "Récolter avant les gelées, pédoncule sec" },
      { mois: [10], titre: "Laisser ressuyer 1 semaine avant stockage" },
    ],
  },
  {
    id: "concombre",
    nom: "Concombre",
    category: "legume",
    emoji: "🥒",
    difficulty: "moyen",
    exposition: "soleil",
    semis: [4, 5],
    plantation: [5, 6],
    recolte: [7, 8, 9],
    arrosage: "Très régulier et abondant. Ne jamais laisser sécher.",
    sol: "Riche, frais, drainé.",
    espacement: "60-80 cm entre plants.",
    compagnonsFavorables: ["Laitue", "Haricot", "Pois", "Maïs"],
    compagnonsDefavorables: ["Tomate", "Pomme de terre", "Courgette", "Radis"],
    conseils:
      "Aime la chaleur : attendre mi-mai pour la pleine terre. Palisser sur un treillis pour gagner de la place et avoir des fruits droits.",
    famille: "Cucurbitacées",
    levee: "6 à 10 jours",
    ravageurs: ["Oïdium", "Araignées rouges"],
    besoinEau: "eleve",
    soins: [
      { mois: [6, 7], titre: "Palisser sur un treillis" },
      { mois: [7, 8], titre: "Récolter jeunes et réguliers" },
    ],
  },
  {
    id: "poivron",
    nom: "Poivron / Piment",
    category: "legume",
    emoji: "🫑",
    difficulty: "moyen",
    exposition: "soleil",
    semis: [2, 3],
    plantation: [5, 6],
    recolte: [7, 8, 9, 10],
    arrosage: "Régulier, sans excès. Sol frais mais drainé.",
    sol: "Riche, bien drainé.",
    espacement: "40-50 cm entre plants.",
    compagnonsFavorables: ["Basilic", "Carotte", "Oignon", "Tomate"],
    compagnonsDefavorables: ["Haricot", "Fenouil"],
    conseils:
      "Semis précoce au chaud (besoin de 20-25°C pour germer). Plante frileuse : ne sortir qu'après tout risque de gel. Adore la chaleur.",
    famille: "Solanacées",
    levee: "10 à 15 jours à 25°C",
    ravageurs: ["Pucerons", "Araignées rouges"],
    besoinEau: "moyen",
    soins: [
      { mois: [6, 7], titre: "Tuteurer les plants chargés de fruits" },
    ],
  },
  {
    id: "aubergine",
    nom: "Aubergine",
    category: "legume",
    emoji: "🍆",
    difficulty: "moyen",
    exposition: "soleil",
    semis: [2, 3],
    plantation: [5, 6],
    recolte: [7, 8, 9, 10],
    arrosage: "Régulier et abondant en été. Sol jamais sec.",
    sol: "Riche, profond, bien drainé.",
    espacement: "50-60 cm entre plants.",
    compagnonsFavorables: ["Haricot", "Thym", "Estragon"],
    compagnonsDefavorables: ["Pomme de terre"],
    conseils:
      "Très frileuse et gourmande en chaleur : semis au chaud (24°C), plantation seulement quand les nuits sont douces. Réussit mieux au sud ou sous serre.",
    famille: "Solanacées",
    levee: "10 à 15 jours à 24°C",
    ravageurs: ["Doryphores", "Araignées rouges"],
    besoinEau: "eleve",
    soins: [
      { mois: [6, 7], titre: "Tuteurer les plants" },
      { mois: [7], titre: "Pincer la tige au-dessus de quelques fruits" },
    ],
  },
  {
    id: "chou",
    nom: "Chou",
    category: "legume",
    emoji: "🥬",
    difficulty: "moyen",
    exposition: "soleil",
    semis: [3, 4, 5, 6],
    plantation: [5, 6, 7],
    recolte: [9, 10, 11, 12],
    arrosage: "Régulier, sol frais. Beaucoup d'eau à la pommaison.",
    sol: "Riche, ferme, frais.",
    espacement: "50-60 cm entre plants.",
    compagnonsFavorables: ["Aromatiques (menthe, thym)", "Céleri", "Betterave"],
    compagnonsDefavorables: ["Fraise", "Tomate", "Ail"],
    conseils:
      "Semer en pépinière puis repiquer. Protéger des chenilles de la piéride avec un filet. Existe en nombreuses variétés (pommé, frisé, de Bruxelles…).",
    famille: "Brassicacées",
    levee: "5 à 10 jours",
    ravageurs: ["Piéride du chou (chenilles)", "Altises", "Mouche du chou"],
    besoinEau: "moyen",
    soins: [
      { mois: [6, 7, 8], titre: "Poser un filet anti-insectes contre la piéride" },
      { mois: [6, 7], titre: "Butter légèrement au pied" },
    ],
  },
  {
    id: "ail",
    nom: "Ail",
    category: "legume",
    emoji: "🧄",
    difficulty: "facile",
    exposition: "soleil",
    semis: [],
    plantation: [10, 11, 2, 3],
    recolte: [6, 7],
    arrosage: "Très faible. Craint l'excès d'humidité.",
    sol: "Léger, drainé, sans fumure fraîche.",
    espacement: "10-12 cm sur le rang, 25-30 cm entre rangs.",
    compagnonsFavorables: ["Fraise", "Tomate", "Carotte", "Framboise"],
    compagnonsDefavorables: ["Haricot", "Pois", "Chou"],
    conseils:
      "Planter les caïeux (gousses) pointe vers le haut. L'ail d'automne donne de plus grosses têtes. Récolter quand le feuillage jaunit et sèche.",
    famille: "Alliacées",
    levee: "Reprise en ~2-3 semaines",
    ravageurs: ["Rouille", "Mouche de l'oignon"],
    besoinEau: "faible",
    soins: [
      { mois: [6, 7], titre: "Récolter quand le feuillage a jauni, par temps sec" },
      { mois: [7], titre: "Faire sécher les têtes à l'ombre, aérées" },
    ],
  },
  {
    id: "echalote",
    nom: "Échalote",
    category: "legume",
    emoji: "🧅",
    difficulty: "facile",
    exposition: "soleil",
    semis: [],
    plantation: [2, 3, 10, 11],
    recolte: [6, 7, 8],
    arrosage: "Faible. Sol drainé indispensable.",
    sol: "Léger, drainé.",
    espacement: "15-20 cm entre bulbes.",
    compagnonsFavorables: ["Carotte", "Fraise", "Laitue"],
    compagnonsDefavorables: ["Haricot", "Pois"],
    conseils:
      "Planter les bulbes pointe affleurant le sol. « À la Sainte-Catherine (25 nov.) ou à la Saint-Joseph (19 mars) ». Récolter au jaunissement des feuilles.",
    famille: "Alliacées",
    levee: "Reprise en ~2 semaines",
    ravageurs: ["Mouche de l'oignon"],
    besoinEau: "faible",
    soins: [
      { mois: [6, 7], titre: "Récolter au jaunissement, faire sécher au sec" },
    ],
  },
  {
    id: "navet",
    nom: "Navet",
    category: "legume",
    emoji: "🫜",
    difficulty: "facile",
    exposition: "soleil",
    semis: [3, 4, 8, 9],
    plantation: [],
    recolte: [5, 6, 10, 11],
    arrosage: "Régulier pour des racines tendres.",
    sol: "Frais, meuble, riche en humus.",
    espacement: "Éclaircir à 10 cm.",
    compagnonsFavorables: ["Pois", "Laitue", "Menthe"],
    compagnonsDefavorables: ["Radis", "Moutarde"],
    conseils:
      "Croissance rapide. Récolter jeune (taille d'une balle de golf à tennis) pour éviter qu'il devienne fibreux et piquant.",
    famille: "Brassicacées",
    levee: "4 à 8 jours",
    ravageurs: ["Altises", "Mouche du chou"],
    besoinEau: "moyen",
    soins: [
      { mois: [4, 8], titre: "Éclaircir à 10 cm" },
    ],
  },
  {
    id: "blette",
    nom: "Blette / Poirée",
    category: "legume",
    emoji: "🥬",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [4, 5, 6],
    plantation: [],
    recolte: [7, 8, 9, 10, 11],
    arrosage: "Régulier, le sol doit rester frais.",
    sol: "Riche, profond, frais.",
    espacement: "35-40 cm entre plants.",
    compagnonsFavorables: ["Chou", "Haricot", "Oignon"],
    compagnonsDefavorables: ["Betterave", "Épinard"],
    conseils:
      "Très facile et productive sur une longue période. Se récolte feuille à feuille (côtes) du centre vers l'extérieur, sur plusieurs mois.",
    famille: "Chénopodiacées",
    levee: "10 à 14 jours",
    ravageurs: ["Pucerons", "Limaces"],
    besoinEau: "moyen",
    soins: [
      { mois: [7, 8, 9, 10], titre: "Récolter les côtes extérieures au besoin" },
    ],
  },
  {
    id: "celeri",
    nom: "Céleri",
    category: "legume",
    emoji: "🥬",
    difficulty: "moyen",
    exposition: "soleil",
    semis: [3, 4],
    plantation: [5, 6],
    recolte: [9, 10, 11],
    arrosage: "Abondant et constant. Plante très gourmande en eau.",
    sol: "Très riche, humifère, frais.",
    espacement: "30-40 cm entre plants.",
    compagnonsFavorables: ["Poireau", "Tomate", "Chou", "Haricot"],
    compagnonsDefavorables: ["Persil", "Carotte"],
    conseils:
      "Demande un sol riche et de l'eau en permanence. Le céleri-branche se blanchit en buttant ; le céleri-rave forme une boule à récolter avant les gelées.",
    famille: "Apiacées",
    levee: "15 à 20 jours",
    ravageurs: ["Mouche du céleri", "Septoriose"],
    besoinEau: "eleve",
    soins: [
      { mois: [8, 9], titre: "Butter pour blanchir (céleri-branche)" },
    ],
  },
  {
    id: "fenouil",
    nom: "Fenouil",
    category: "legume",
    emoji: "🥬",
    difficulty: "moyen",
    exposition: "soleil",
    semis: [5, 6, 7],
    plantation: [],
    recolte: [8, 9, 10, 11],
    arrosage: "Régulier, sol frais pour éviter la montée à graine.",
    sol: "Profond, frais, drainé.",
    espacement: "30 cm entre plants.",
    compagnonsFavorables: ["Concombre", "Laitue"],
    compagnonsDefavorables: ["Tomate", "Haricot", "Poivron"],
    conseils:
      "Le fenouil bulbeux se sème en été pour une récolte d'automne. Butter le bulbe pour le blanchir. Mauvais voisin de beaucoup de cultures : l'isoler.",
    famille: "Apiacées",
    levee: "10 à 14 jours",
    ravageurs: ["Pucerons"],
    besoinEau: "moyen",
    soins: [
      { mois: [8, 9], titre: "Butter le bulbe pour le blanchir" },
    ],
  },
  {
    id: "mache",
    nom: "Mâche",
    category: "legume",
    emoji: "🥬",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [8, 9, 10],
    plantation: [],
    recolte: [10, 11, 12, 1, 2, 3],
    arrosage: "Régulier à la levée, faible ensuite.",
    sol: "Ordinaire, ferme, frais.",
    espacement: "Éclaircir à 10 cm.",
    compagnonsFavorables: ["Poireau", "Choux"],
    compagnonsDefavorables: [],
    conseils:
      "La salade de l'hiver : semer en fin d'été/automne sur sol tassé. Très rustique, se récolte par temps froid. Couper la rosette entière au ras du sol.",
    famille: "Valérianacées",
    levee: "10 à 20 jours",
    ravageurs: ["Limaces", "Oïdium"],
    besoinEau: "faible",
    soins: [
      { mois: [10, 11, 12, 1, 2], titre: "Récolter les rosettes au ras du sol" },
    ],
  },
  {
    id: "roquette",
    nom: "Roquette",
    category: "legume",
    emoji: "🌿",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [3, 4, 5, 8, 9],
    plantation: [],
    recolte: [4, 5, 6, 9, 10, 11],
    arrosage: "Régulier ; la sécheresse la rend très piquante.",
    sol: "Frais, ordinaire.",
    espacement: "Éclaircir à 10 cm.",
    compagnonsFavorables: ["Laitue", "Épinard"],
    compagnonsDefavorables: [],
    conseils:
      "Pousse très vite (4-6 semaines). Récolter feuille à feuille. Monte vite en graine par chaleur : préférer printemps et automne, ressemer souvent.",
    famille: "Brassicacées",
    levee: "5 à 8 jours",
    ravageurs: ["Altises"],
    besoinEau: "moyen",
    soins: [
      { mois: [3, 4, 8, 9], titre: "Ressemer toutes les 3 semaines" },
    ],
  },
  {
    id: "melon",
    nom: "Melon",
    category: "legume",
    emoji: "🍈",
    difficulty: "difficile",
    exposition: "soleil",
    semis: [3, 4],
    plantation: [5, 6],
    recolte: [7, 8, 9],
    arrosage: "Régulier jusqu'à la formation des fruits, puis réduire pour concentrer le sucre.",
    sol: "Très riche, chaud, drainé.",
    espacement: "1 m entre plants.",
    compagnonsFavorables: ["Maïs", "Capucine"],
    compagnonsDefavorables: ["Concombre", "Courgette"],
    conseils:
      "Exigeant en chaleur : réussite plus facile au sud ou sous abri. Tailler (pincer) pour limiter à quelques fruits par pied et les faire mûrir.",
    famille: "Cucurbitacées",
    levee: "5 à 8 jours à 25°C",
    ravageurs: ["Oïdium", "Pucerons"],
    besoinEau: "eleve",
    soins: [
      { mois: [6, 7], titre: "Pincer la tige pour favoriser les ramifications" },
      { mois: [7, 8], titre: "Placer une tuile/planche sous les fruits" },
    ],
  },

  // ---------------- AROMATES ----------------
  {
    id: "basilic",
    nom: "Basilic",
    category: "aromate",
    emoji: "🌿",
    difficulty: "facile",
    exposition: "soleil",
    semis: [3, 4, 5],
    plantation: [5, 6],
    recolte: [6, 7, 8, 9, 10],
    arrosage: "Régulier, le matin. Craint la sécheresse comme l'excès d'eau.",
    sol: "Riche, frais, drainé.",
    espacement: "20-25 cm entre plants.",
    compagnonsFavorables: ["Tomate", "Poivron", "Courgette"],
    compagnonsDefavorables: [],
    conseils:
      "Frileux : ne pas sortir avant mi-mai. Pincer régulièrement les sommités pour le rendre touffu et empêcher la floraison. Parfait en pot sur un rebord ensoleillé.",
    famille: "Lamiacées",
    levee: "5 à 10 jours",
    ravageurs: ["Pucerons", "Limaces (jeunes plants)"],
    besoinEau: "moyen",
    soins: [
      { mois: [6, 7, 8, 9], titre: "Pincer les sommités, retirer les fleurs" },
    ],
  },
  {
    id: "persil",
    nom: "Persil",
    category: "aromate",
    emoji: "🌿",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [3, 4, 5, 6, 7, 8],
    plantation: [],
    recolte: [5, 6, 7, 8, 9, 10, 11],
    arrosage: "Régulier, le sol doit rester frais.",
    sol: "Riche, frais, profond.",
    espacement: "Éclaircir à 15-20 cm.",
    compagnonsFavorables: ["Tomate", "Carotte", "Radis"],
    compagnonsDefavorables: ["Laitue"],
    conseils:
      "Germination lente (3 semaines) : faire tremper les graines 24h avant le semis. Bisannuel : produit tout l'été, monte en graine la 2e année.",
    famille: "Apiacées",
    levee: "20 à 30 jours",
    ravageurs: ["Mouche de la carotte"],
    besoinEau: "moyen",
    soins: [
      { mois: [5, 6, 7, 8, 9], titre: "Couper les tiges extérieures au besoin" },
    ],
  },
  {
    id: "ciboulette",
    nom: "Ciboulette",
    category: "aromate",
    emoji: "🌱",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [3, 4, 5],
    plantation: [3, 4, 9, 10],
    recolte: [4, 5, 6, 7, 8, 9, 10],
    arrosage: "Régulier, aime les sols frais.",
    sol: "Riche, frais.",
    espacement: "20-25 cm entre touffes.",
    compagnonsFavorables: ["Carotte", "Tomate", "Rosier"],
    compagnonsDefavorables: ["Haricot", "Pois"],
    conseils:
      "Vivace : revient chaque année. Couper à 2 cm du sol pour stimuler de nouvelles pousses. Diviser la touffe tous les 3 ans.",
    famille: "Alliacées",
    levee: "10 à 20 jours",
    ravageurs: ["Rouille (rare)"],
    besoinEau: "moyen",
    soins: [
      { mois: [4, 5, 6, 7, 8, 9], titre: "Couper à 2 cm du sol pour relancer" },
      { mois: [3], titre: "Diviser les touffes âgées de 3 ans" },
    ],
  },
  {
    id: "thym",
    nom: "Thym",
    category: "aromate",
    emoji: "🌿",
    difficulty: "facile",
    exposition: "soleil",
    semis: [3, 4, 5],
    plantation: [4, 5, 9, 10],
    recolte: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    arrosage: "Très faible. Supporte très bien la sécheresse.",
    sol: "Pauvre, sec, caillouteux, très drainé.",
    espacement: "30 cm entre plants.",
    compagnonsFavorables: ["Chou", "Tomate", "Aubergine"],
    compagnonsDefavorables: [],
    conseils:
      "Vivace et rustique : se récolte toute l'année. Surtout ne pas trop arroser, il déteste l'humidité. Idéal en bordure ou en pot.",
    famille: "Lamiacées",
    levee: "15 à 25 jours",
    ravageurs: ["Aucun majeur (plante très robuste)"],
    besoinEau: "faible",
    soins: [
      { mois: [4], titre: "Tailler légèrement pour garder une touffe compacte" },
    ],
  },
  {
    id: "menthe",
    nom: "Menthe",
    category: "aromate",
    emoji: "🌱",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [4, 5],
    plantation: [3, 4, 5, 9, 10],
    recolte: [5, 6, 7, 8, 9, 10],
    arrosage: "Régulier, aime l'humidité.",
    sol: "Frais, riche, humide.",
    espacement: "30-40 cm, ou en pot.",
    compagnonsFavorables: ["Chou", "Tomate"],
    compagnonsDefavorables: ["Persil", "Camomille"],
    conseils:
      "Très envahissante : à cultiver en pot ou avec une barrière anti-racines, sinon elle colonise tout le jardin. Vivace, revient chaque année.",
    famille: "Lamiacées",
    levee: "10 à 15 jours",
    ravageurs: ["Rouille de la menthe"],
    besoinEau: "moyen",
    soins: [
      { mois: [6, 7, 8], titre: "Couper les tiges pour stimuler de jeunes pousses" },
      { mois: [4], titre: "Contenir les racines (pot, barrière)" },
    ],
  },
  {
    id: "coriandre",
    nom: "Coriandre",
    category: "aromate",
    emoji: "🌿",
    difficulty: "facile",
    exposition: "soleil",
    semis: [4, 5, 6, 7],
    plantation: [],
    recolte: [6, 7, 8, 9],
    arrosage: "Régulier pour retarder la montée en graine.",
    sol: "Léger, drainé.",
    espacement: "Éclaircir à 15 cm.",
    compagnonsFavorables: ["Anis", "Concombre", "Chou"],
    compagnonsDefavorables: ["Fenouil"],
    conseils:
      "Semer directement (supporte mal le repiquage). Monte vite en graine par temps chaud : semer un peu, souvent, et de préférence à la mi-ombre en été.",
    famille: "Apiacées",
    levee: "7 à 20 jours",
    ravageurs: ["Pucerons"],
    besoinEau: "moyen",
    soins: [
      { mois: [5, 6, 7], titre: "Ressemer toutes les 3 semaines (monte vite)" },
    ],
  },
  {
    id: "romarin",
    nom: "Romarin",
    category: "aromate",
    emoji: "🌿",
    difficulty: "facile",
    exposition: "soleil",
    semis: [],
    plantation: [4, 5, 9, 10],
    recolte: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    arrosage: "Très faible une fois installé. Résiste à la sécheresse.",
    sol: "Pauvre, sec, très drainé, plutôt calcaire.",
    espacement: "80 cm à 1 m (devient un arbuste).",
    compagnonsFavorables: ["Chou", "Carotte", "Sauge"],
    compagnonsDefavorables: [],
    conseils:
      "Arbuste vivace : planter plutôt qu'à semer (germination difficile). Se récolte toute l'année. Craint surtout l'excès d'eau en hiver.",
    famille: "Lamiacées",
    levee: "Multiplication par bouturage conseillée",
    ravageurs: ["Chrysomèle du romarin"],
    besoinEau: "faible",
    soins: [
      { mois: [4, 5], titre: "Tailler après la floraison pour densifier" },
    ],
  },
  {
    id: "sauge",
    nom: "Sauge officinale",
    category: "aromate",
    emoji: "🌿",
    difficulty: "facile",
    exposition: "soleil",
    semis: [4, 5],
    plantation: [4, 5, 9, 10],
    recolte: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    arrosage: "Faible. Résiste bien à la sécheresse.",
    sol: "Léger, drainé, calcaire.",
    espacement: "40-50 cm entre plants.",
    compagnonsFavorables: ["Chou", "Carotte", "Romarin"],
    compagnonsDefavorables: ["Concombre"],
    conseils:
      "Vivace robuste, feuillage persistant récoltable toute l'année. Tailler au printemps pour éviter qu'elle ne se dégarnisse. Mellifère.",
    famille: "Lamiacées",
    levee: "15 à 20 jours",
    ravageurs: ["Oïdium (si trop d'humidité)"],
    besoinEau: "faible",
    soins: [
      { mois: [3, 4], titre: "Tailler les tiges sèches pour redensifier" },
    ],
  },

  // ---------------- FRUITS ----------------
  {
    id: "fraise",
    nom: "Fraise",
    category: "fruit",
    emoji: "🍓",
    difficulty: "facile",
    exposition: "soleil",
    semis: [],
    plantation: [3, 4, 8, 9],
    recolte: [5, 6, 7, 8, 9],
    arrosage: "Régulier au pied, sans mouiller les fruits.",
    sol: "Riche, frais, drainé, légèrement acide.",
    espacement: "30-40 cm entre plants.",
    compagnonsFavorables: ["Laitue", "Épinard", "Haricot", "Ail"],
    compagnonsDefavorables: ["Chou"],
    conseils:
      "Planter des plants (en godet) plutôt que semer. Pailler le sol pour garder les fruits propres et l'humidité. Renouveler les pieds tous les 3 ans.",
    famille: "Rosacées",
    levee: "Plantation en godet (pas de semis)",
    ravageurs: ["Limaces", "Oïdium", "Pourriture grise"],
    besoinEau: "moyen",
    soins: [
      { mois: [3, 4], titre: "Pailler le pied (paille, tonte sèche)" },
      { mois: [6, 7, 8], titre: "Couper les stolons pour renforcer les pieds" },
    ],
  },
  {
    id: "framboise",
    nom: "Framboise",
    category: "fruit",
    emoji: "🍇",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [],
    plantation: [10, 11, 2, 3],
    recolte: [6, 7, 8, 9, 10],
    arrosage: "Régulier, surtout pendant la fructification.",
    sol: "Frais, riche, drainé, légèrement acide.",
    espacement: "50 cm entre pieds, palissés sur fils.",
    compagnonsFavorables: ["Ail", "Œillet d'Inde"],
    compagnonsDefavorables: ["Pomme de terre", "Tomate"],
    conseils:
      "Planter des cannes en automne ou fin d'hiver. Palisser sur des fils de fer. Tailler après récolte : supprimer les cannes ayant fructifié.",
    famille: "Rosacées",
    levee: "Plantation de cannes (pas de semis)",
    ravageurs: ["Ver des framboises", "Rouille"],
    besoinEau: "moyen",
    soins: [
      { mois: [2, 3], titre: "Palisser les cannes sur des fils" },
      { mois: [10, 11], titre: "Tailler les cannes ayant fructifié" },
    ],
  },
  {
    id: "cassis",
    nom: "Cassis",
    category: "fruit",
    emoji: "🫐",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [],
    plantation: [10, 11, 12, 2, 3],
    recolte: [6, 7, 8],
    arrosage: "Régulier, surtout en été et à la fructification.",
    sol: "Riche, frais, profond.",
    espacement: "1,5 m entre arbustes.",
    compagnonsFavorables: ["Œillet d'Inde"],
    compagnonsDefavorables: ["Groseillier (parfois mêmes maladies)"],
    conseils:
      "Arbuste rustique planté à l'automne (à racines nues). Aime les situations un peu fraîches. Tailler en hiver pour renouveler les vieilles branches.",
    famille: "Grossulariacées",
    levee: "Plantation d'arbuste (pas de semis)",
    ravageurs: ["Pucerons", "Oïdium américain"],
    besoinEau: "moyen",
    soins: [
      { mois: [11, 12, 1, 2], titre: "Tailler les branches de plus de 3 ans" },
    ],
  },
  {
    id: "groseille",
    nom: "Groseille",
    category: "fruit",
    emoji: "🍒",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [],
    plantation: [10, 11, 12, 2, 3],
    recolte: [6, 7, 8],
    arrosage: "Régulier en été. Tolère la sécheresse modérée une fois installé.",
    sol: "Frais, drainé, riche en humus.",
    espacement: "1,2 à 1,5 m entre arbustes.",
    compagnonsFavorables: ["Œillet d'Inde"],
    compagnonsDefavorables: [],
    conseils:
      "Très facile et rustique, supporte la mi-ombre. Planter à l'automne. Tailler en hiver pour aérer le centre de l'arbuste et renouveler le bois.",
    famille: "Grossulariacées",
    levee: "Plantation d'arbuste (pas de semis)",
    ravageurs: ["Pucerons", "Tenthrède (chenilles défoliatrices)"],
    besoinEau: "moyen",
    soins: [
      { mois: [11, 12, 1, 2], titre: "Tailler pour aérer le centre de l'arbuste" },
    ],
  },
  {
    id: "rhubarbe",
    nom: "Rhubarbe",
    category: "fruit",
    emoji: "🌿",
    difficulty: "facile",
    exposition: "mi-ombre",
    semis: [],
    plantation: [3, 4, 9, 10],
    recolte: [4, 5, 6, 7],
    arrosage: "Régulier, aime les sols frais et profonds.",
    sol: "Très riche, profond, frais.",
    espacement: "1 m (la plante devient imposante).",
    compagnonsFavorables: ["Chou", "Haricot"],
    compagnonsDefavorables: [],
    conseils:
      "Vivace très longue durée (10 ans et +). Planter un éclat de souche. Ne pas récolter la 1re année. Ne consommer que les pétioles (les feuilles sont toxiques).",
    famille: "Polygonacées",
    levee: "Plantation d'éclat de souche (pas de semis)",
    ravageurs: ["Limaces (jeunes pousses)"],
    besoinEau: "moyen",
    soins: [
      { mois: [4, 5, 6], titre: "Récolter les pétioles en tirant (ne pas couper)" },
      { mois: [6, 7], titre: "Supprimer les hampes florales pour préserver la plante" },
    ],
  },
];

export function getPlantById(id: string): Plant | undefined {
  return PLANTS.find((p) => p.id === id);
}
